apiVersion: nerworking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-demo
spec:
  ingressClassName:
    rules:
      - host: localhost
        http:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: webook
                port:
                  number: 80